### ISSUE TITLE
use of volume cause 'unable to connect to service' error?

### ISSUE THREAD

**Issue by dpastoor** [rocker-org/rstudio-daily#3]
Running on a refresh ubuntu server image, when doing

```
 docker run -d -p 8787:8787 -v $(pwd):/home/rstudio rocker/rstudio-daily
```

I get the login screen, but after logging in it just hangs for a bit then get 

![image](https://user-images.githubusercontent.com/3196313/27187257-b3bdb3d8-51b8-11e7-8fea-e0d123c22fa7.png)

removing the -v

```
 docker run -d -p 8787:8787 rocker/rstudio-daily
```

and it works fine, of course sans the mount to the file system.

This issue is also presenting with the regular rstudio image. Any ideas how to try to debug? I've tried mounting different folders, using abolute paths explicitly over $(pwd) but nothing seems to work.

**Comment by eddelbuettel** [comment]
Just thinking out aloud here:  Can you try any other directory?  Below `$HOME` is of course where the user has her stateful file so there be an old-fashioned race or permissions issue going on.

**Comment by dpastoor** [comment]
Good thought!  I was looking the problem was on the host side. You are correct - there is something going on in `/home` in the container

trying to map to `\data` works!
```
docker run -d -p 8788:8787 -v /home/devin/data:/data rocker/rstudio-daily
```

though trying to map to `/home` or `/home/rstudio` does not.

**Comment by dpastoor** [comment]
Ok, looks like something is just bad about how I installed docker. I am unable to replicate this on other machines, and after destroying this and spinning up a fresh digital ocean server with docker everything is working.

**Comment by drspangle** [comment]
I just had this same error and discovered that there were two reasons for the problem. The first was that the folder which I was trying to volume mount didn't have `docker` group ownership. The second was that there was not group read and write permissions applied. You can fix this in a pinch with `chown -R :docker <directory>` and `chmod 777 <directory>`.

**Comment by eddelbuettel** [comment]
Note that that gives 'global' read/write/exec which may be more than you want, depending on the circumstances.  0775 may be preferable, group owner docker, and make yourself member of group docker.
