### ISSUE TITLE
Rstudio with singularity

### ISSUE THREAD

**Issue by HelenCousins** [rocker-org/rstudio-daily#4]
https://www.rocker-project.org/use/singularity/  suggests rocker/rstudio works with singularity.  I managed to build a .simg, excellent.  Then I tried

  singularity exec rstudio.simg rserver

and, well

10 Apr 2019 14:03:34 [rserver] ERROR R did not return any output when queried for directory location information; LOGGED FROM: bool rstudio::core::r_util::{anonymous}::detectRLocationsUsingR(const string&, rstudio::core::FilePath*, rstudio::core::FilePath*, rstudio::core::config_utils::Variables*, std::string*) /home/ubuntu/rstudio/src/cpp/core/r_util/REnvironmentPosix.cpp:483
10 Apr 2019 14:03:34 [rserver] ERROR system error 71 (Protocol error) [description=Unable to parse version from R, version-info=, r-error=/usr/local/lib/R/bin/exec/R: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libquadmath.so.0: invalid ELF header
]; OCCURRED AT: rstudio::core::Error rstudio::core::r_util::rVersion(const rstudio::core::FilePath&, const rstudio::core::FilePath&, const string&, std::string*) /home/ubuntu/rstudio/src/cpp/core/r_util/REnvironmentPosix.cpp:784; LOGGED FROM: bool rstudio::core::r_util::detectREnvironment(const rstudio::core::FilePath&, const rstudio::core::FilePath&, const string&, std::string*, std::string*, rstudio::core::r_util::EnvironmentVars*, std::string*) /home/ubuntu/rstudio/src/cpp/core/r_util/REnvironmentPosix.cpp:678

I am unsure of what this means.

**Comment by eitsupi** [comment]
For issues related to singularity, please search the https://github.com/rocker-org/rocker-versioned2 repository.
